
sudo: false
dist: trusty
language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

addons:
  chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm run pkg:lint
  - npm run pkg:test
  - npm run pkg:build
  - npm run int:lint
  - npm run int:test
  - npm run int:build
  - xvfb-run npm run int:e2e
