
sudo: false
dist: trusty
language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint:cfg
  - npm run test:cfg
  - npm run build:cfg
  - npm run build:web
  - xvfb-run npm run e2e web-e2e
