
sudo: false
dist: trusty
language: node_js
node_js:
  - "9"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - yarn

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn ci

after_script:
  - cat ./coverage/cfg/lcov.info | ./node_modules/coveralls/bin/coveralls.js
